### ISSUE TITLE
webpack integration

### ISSUE THREAD

**Issue by m1llen1um** [loedeman/AutoMapper#12]
This library looks vary promising and I want to integrate it in our new project, but I have some **problems integrating it with webpack**. Also will be great if there is a [Typings](https://github.com/typings/typings) which we can include in our typings.json

Simple example I'm trying to make run: 

1. Create project from _[yo generator-typescript-webpack](https://www.npmjs.com/package/generator-typescript-webpack)_
2. npm i automapper-ts
3. try to import automapper and log object to console

I'll appreciate any clue or advise which you can give. Thank you!

**Comment by loedeman** [comment]
Hi, I have never worked with WebPack myself, I am afraid I can't help you much on that part. Feel free to fill me in with more details, maybe I can help more if I understand what is going wrong... 

A TypeScript definition file is available in the /dist/ folder.

**Comment by m1llen1um** [comment]
Hi, thanks for the feedback! I find a way to run your lib. Still it's walkaround. Here is my repo with a
[demo app](https://github.com/m1llen1um/fooapps-automapper-ts).

I had to **modify** the **automapper.d.ts** so the webpack (with commonjs) can find it as a module. I will go with this approach unless you can offer better solution. Still [Typings](https://github.com/typings/typings) will be great.

**Comment by loedeman** [comment]
Hi @m1llen1um, I would suggest you to try the 1.7.0 release. This release should fix your issue (alongside others ;)). Good luck and happy coding! Cheers, Bert
