### ISSUE TITLE
Small correction for Getting Started Guide

### ISSUE THREAD

**Issue by GregOnNet** [loedeman/AutoMapper#18]
Hi,

thanks for bringing `AutoMapper` to the JS-World. :tada: 

I experienced another mapping-behavior than described in the wiki.

When I use the following sample (written below) I expect to get *Result A* but I get *Result B*.
Since `prop1` has a value in the sourceType `mapFrom` seems not to be respected in the map.

- If I change the name of `prop2`, `mapFrom` works.

## Sample
```javascript
var objA = { prop1: 'From A', prop2: 'From A too', prop3: 'Also from A (really)' };

automapper
    .createMap('sourceType', 'destinationType')
    .forMember('prop1', function (opts) { opts.mapFrom('prop2'); }) 
    // changing 'prop2' to e.g. 'destProp2' everything works correctly.
    .forMember('prop2', function (opts) { opts.ignore(); })
    .forSourceMember('prop3', function (opts) { opts.ignore(); })
    .forMember('prop4', function () { return 12; })

var objB = automapper.map('sourceType', 'destinationType', objA);
```

### Result A

```json
{
  "prop1": "From A too", 
  "prop4": 12 
}
```

### Result B

```json
{
  "prop1": "From A", 
  "prop4": 12 
}
```

If you need further information, please contact me.

Thanks in advance
Gregor

**Comment by loedeman** [comment]
Hi Gregor,

Thanks a lot for reporting! I will look into this issue soon. You are definitely right that Result A is the result you should expect. I wonder why hundreds of people use the library without ever stumbling upon this one ;) ...

Cheers, Bert

**Comment by loedeman** [comment]
Hi Gregor,

Just reproduced this issue using a Jasmine unit test, but discovered this (apparently small) issue needs a major overhaul of the AutoMapper core. Since there is almost 100% code coverage, this won't be a big deal, but still a major time consumer. I have to find a free night to get this one done. I hope this won't bother you too much!

Cheers, Bert

**Comment by GregOnNet** [comment]
Hi Bert,

thanks for diving deeper into the problem.
I have no problem to wait.

Kinds
Gregor

**Comment by loedeman** [comment]
Hi @GregOnNet,

I just created release 1.8.0 (https://github.com/loedeman/AutoMapper/tree/1.8.0), which contains a fix for the issue you created. Please let me know if you encounter any issue (or create a PR to fix them if you feel like it ;-) ). Thanks!

Happy coding!

**Comment by GregOnNet** [comment]
Hi @loedeman,

it works :tada:.
Thanks for your support.

Kinds
Greg
