### ISSUE TITLE
Map and ignore mapped value

### ISSUE THREAD

**Issue by eugenekgn** [loedeman/AutoMapper#21]
Let's say I have the following objects
```
A: {
  a: 'xx' 
  b: 'yy'
}

B: {
  a: 'xx2' 
  b: 'yy2'
}
```

lets say I map B.b => A.a, and ignore B.b.

this code crashes 

```
  mapper.createMap(map, BtoA)
      .forMember('a', (opts) => {
        return opts.sourceObject.b;
      }
       .forMember('a', (opts) => {
        opts.ignore();
      })
```

**Comment by loedeman** [comment]
Hi @eugenekgn,

Wow, that's a complex piece of code you are presenting :)... Could you please upload the full code crashing (including 'map', 'BtoA' and potential other code pieces leading to your situation - maybe a zip/rar)? Of course I will be more than happy to reproduce your issue and hopefully to present a fix asap.

Cheers, Bert

**Comment by eugenekgn** [comment]
Hi there,

It would be fairly challenging to isolate this use case, I might be explaining this clear enough but all I am trying to do is map property {B.b} to {A.a} , and since B object still has property B.a has the same named property which A has which is {A.a} I am trying to prevent auto mapping. 

The outcome that I want to have is the following

```
  A: {
     a: "yy2" // I get a's value from B.b but automapper tries to Map B.a to = A.a because they have the same property names, 
  }
 ```

Please let me know if this make more sense.

**Comment by loedeman** [comment]
Hi @eugenekgn,

I think I partly understand what you are trying to do. What is going wrong obviously, is the following: when you map destination member a and ignore the same destination member afterwards, the result will be that there is no A.a property at all. You could of course try to ignore the source member (forSourceMember) instead, although I don't get why you should need that as well ;) ...

Cheers, Bert
