### ISSUE TITLE
Automapping of arrays does not work?

### ISSUE THREAD

**Issue by Frankst2** [loedeman/AutoMapper#24]
Hi,
I'm not sure if this is a real issue and/or just an unsupported usage of AutoMapper: I wonder if I should be able to use arrays for the mapping (in mapFrom). E.g. take the following map in JavaScript:
automapper
        .createMap('sourceType', 'destinationType')
        .forMember('description', function (opts) { opts.mapFrom('Ticket[0].Title'); })
        .forMember('severity', function (opts) { opts.mapFrom('Ticket[0].Priority'); });

I would expect that it takes the first entry from "Ticket" array, picks the "Title" and then stores it in the "description" property. This does not seem to work, it just returns the original data (or empty, if I use ignoreAllNonExisting()).

**Comment by loedeman** [comment]
Hi @Frankst2 ,

The .mapFrom function does require you specify a property name. Providing an array indexer won't work. You should try using intermediate values instead. Please have a look at the Jasmine tests for usage examples ;) ...

Cheers, Bert
