### ISSUE TITLE
Empty object when the mappings return undefined for the object properties?

### ISSUE THREAD

**Issue by Frankst2** [loedeman/AutoMapper#26]
I noticed the automapper creates an empty object when all the mapped properties of an object are undefined. I'm not sure if this is by design or just an issue that's rather difficult to prevent (in a clean way).

Example:
```
automapper
  .createMap('sourceType', 'destinationType')
  .forMember('foo.Title', function (opts) { opts.mapFrom('description'); })
  .forMember('foo.State', function (opts) { opts.mapFrom('status'); })
  .forMember('foo.Priority', function (opts) { opts.mapFrom('severity')});
```
All the mapFrom properties don't exist in the source object, so they are undefined. In the resulting output there exists an empty foo object.

**Comment by loedeman** [comment]
Hi @Frankst2,

Sorry for reacting so late. It has been quite a busy time over here lately ;) . This is indeed a very complex problem to solve properly. The most efficient way to overcome this problem would probably be:

1. Create a hidden property (e.g. __propertiesSet: boolean) on the destination object when a property is set successfully.
2. Check for (and remove!) the hidden property just before returning or adding to the array.

It will come at some extra cost, and, I think it's a little ugly ;) . Should you feel like it, please feel free to fork the library and create a PR for your fix ;) ...

Cheers, Bert

**Comment by Frankst2** [comment]
Actually I'm not even sure anymore why I filed this issue back then ;) since actually an empty object is not a big problem, it's just what it is. So I guess I found a way to deal with this problem.

**Comment by loedeman** [comment]
Top, sounds like you have found a workaround ;) . Thanks for using AutoMapperTS, enjoy!
