### ISSUE TITLE
Nested objects

### ISSUE THREAD

**Issue by ialex90** [loedeman/AutoMapper#30]
Hi there,

Thanks for the work on the library.

More than an error, just a question. Do you have any way to handle nested objects?  I saw on the documentation that the link is red and pointing somewhere else, so I assume is not implemented, can you please confirm that?

In that case, is there any workaround for nested object you would recommend?

Thanks in advance,

**Comment by ialex90** [comment]
I have a workaround which is mapping firs the parent and then mapping the child within the parent, just to know your opinion on there

**Comment by loedeman** [comment]
Hi @ialex90 ,

Thanks for reaching out. Mapping nested objects (both flattening and nesting) is fully implemented in AutoMapperTS. Maintaining the wiki is quite a hassle, I apparently did not keep it up to date completely (sorry for that ;) ). Luckily, all you should need is 'documented' by a couple of Jasmine unit tests, which you can find at the following location: https://github.com/loedeman/AutoMapper/blob/master/test/tests/ts/automapper-createmap-formember-specs.ts.

Happy coding! Bert

**Comment by ialex90** [comment]
Ouh yeah, thanks @loedeman this library rocks :)

`            .forMember('address', (opts: AutoMapperJs.IMemberConfigurationOptions) => opts.mapFrom('address'))
            .forMember('address', (opts: AutoMapperJs.IMemberConfigurationOptions) =>
                automapper.map(AddressResponse.name, Address.name, opts.intermediatePropertyValue))
`

Doing that, make the nested mapping with a previously registered config.

Great job kudos for you, I am having some ideas for this library which could be really nice to have, hopefully I am getting some free time over the weeks and will try to do a PR.

Cheers,
