### ISSUE TITLE
Can't override default values....

### ISSUE THREAD

**Issue by jphilippakos** [loedeman/AutoMapper#32]
Since the typescript 2.4 update, it seems like the entire logic behind automapper has changed, which causes many breaking changes. The first was that while in the past, the source object was the standard, and all properties got copied, now the target comes first and only those properties you declare in your class will be copied. While I do not feel that this is the best logic for js/ts, it is easy enough to remedy. The one major shortfall in the new logic however, is that we are no longer able to set default values in our classes, because any property that has a value set will be ignored. at the vary least we should have the option to override the target. Am I missing this option, or is it in fact not implemented? Also, is there any chance of it being implemented in the future?

**Comment by loedeman** [comment]
Hi @jphilippakos, thanks for getting in touch! I am not entirely sure I do understand what you are saying. I am not aware that I changed logic at all lately. Are you suggesting the JavaScript of the latest NPM package is behaving differently compared to other releases? Or are you using AutoMapper TypeScript source code directly in your project, resulting in any unexpected behavior? Cheers, Bert

**Comment by jphilippakos** [comment]
Hi, sorry, I should have been more clear! It wasn't a recent change, we just recently ran into it since we had put off updating for a while.  The change was from 1.7.3 to 1.8.0. Before that update, all properties from the source object were copied (or ran through forMember), regardless of the structure of the target class. Ever since that update, it only copies properties that are declared in the current class, and that are not defined in the constructor. Declaring the properties, though not always ideal, is not a big deal.... However, if we are using a class that was not created solely to be used with automapper, we have to jump through hoops to set default values on the properties of the class, since automapper will now ignore any properties that have a value. I have not been able to find an option that will allow overriding existing values, my apologies if I missed something.

**Comment by loedeman** [comment]
I think I get your point. I was not aware of this behavior at all. In other words, you were using a hidden gem ;) ... Would it be helpful to create a function like the (existing) counterpart `ignoreAllNonExisting`?

**Comment by jphilippakos** [comment]
so an overrideExisting flag? That would definitely do the trick.... Especially if we can also make it a global setting when initializing automapper :)

Thank you!

**Comment by loedeman** [comment]
Hi @jphilippakos, if the problem still occurs, could you please attach a small piece of sample code (a source and destination class, the mapping registration and calling code) to make this easier to reproduce for me?

**Comment by jphilippakos** [comment]
I'm sorry for my delayed response. Using the latest version (1.8.3) or automapper-ts I haven't seen a difference.... Here is my sample code....

```
import "automapper-ts";

class SampleClass {
    propA = "class Property A";
    propB: string;
    propC: Date = null;
}

let source = {
    propA: "source Property A",
    propC: "1/10/2017",
    propD: "source Property D"
}

automapper.createMap("any", "SampleClass").convertToType(SampleClass)
    .forMember("propC", (opts: AutoMapperJs.IMemberConfigurationOptions) => {
        let val = opts.sourceObject[opts.sourcePropertyName];
        return new Date(val);
    });

let mapped = automapper.map("any", "SampleClass", source);

console.log(mapped);
import "automapper-ts";

class SampleClass {
    propA = "class Property A";
    propB: string;
    propC: Date = null;
}

let source = {
    propA: "source Property A",
    propC: "1/10/2017",
    propD: "source Property D"
}

automapper.createMap("any", "SampleClass").convertToType(SampleClass)
    .forMember("propC", (opts: AutoMapperJs.IMemberConfigurationOptions) => {
        let val = opts.sourceObject[opts.sourcePropertyName];
        return new Date(val);
    });

let mapped = automapper.map("any", "SampleClass", source);

console.log(mapped);
```
This is what I get....
SampleClass { propA: 'class Property A', propC: 2017-01-09T22:00:00.000Z }

However I expect to get...
SampleClass { propA: 'source Property A', propC: 2017-01-09T22:00:00.000Z }

(or even better....)
SampleClass { propA: 'class Property A', propC: 2017-01-09T22:00:00.000Z , propD: 'source Property D'}

**Comment by Toilal** [comment]
Same issue here. I run TypeScript 2.6.1.

Default values defined in classes are kept instead of being overriden during the mapping result.

**Comment by Toilal** [comment]
After debugging the unit test from #42, the issue is caused by this condition : 

https://github.com/loedeman/AutoMapper/blob/8b3a230755814233acbd838abc5718a5636cbc46/src/ts/AutoMapperBase.ts#L88-L90

Comment seems to indicate an absuption that is wrong when using default value in classes.

**Comment by Toilal** [comment]
The issue only occurs when property is not configured on the mapping.

Adding `.forMember('prop', opts => opts.mapFrom('prop'))` to the mapping configuration should help to workaround the issue.
