### ISSUE TITLE
Mismatched sourcemap automapper.js.map

### ISSUE THREAD

**Issue by hirikarate** [loedeman/AutoMapper#34]
Version: 1.8.2
IDE: Visual Studio Code 1.14.2

When I removed file `automapper.js.map` from folder `node_modules/automapper-ts/dist`, the step debugger (F11) correctly jumps to first line of the `map` function. As you can see in screenshot, it is line 1004 in file `automapper.js`.

![image](https://user-images.githubusercontent.com/5905553/28663305-328971b2-72e7-11e7-881d-c2b31d94272f.png)

In contrary, when file `automapper.js.map` is kept, the step debugger uses that file to re-construct a temporary source file named "AutoMapper.js", but it jumps to incorrect position. In the screenshot, the debugger mistake line 92 as the first line of `map` function. Continuing to press F10 will step to outside of `map` function and cross the next one.

![image](https://user-images.githubusercontent.com/5905553/28663319-3ca678d4-72e7-11e7-978b-7bb86d2fbc99.png)

**Comment by loedeman** [comment]
Hi @hirikarate , this should be fixed in v1.8.3... Cheers!
