### ISSUE TITLE
Destination member configured but does not exist on destination.

### ISSUE THREAD

**Issue by appsolutegeek** [loedeman/AutoMapper#35]
Hi,

I was using automapper by creating maps using strings before but I wanted to use the assetConfigurationIsValid but its reporting errors that I do not think are correct. 

I got the following error.

```
throw new Error("Mapping '" + mappingKey + "' is invalid: " + errorMessage + " (source: '" + sourceClassName + "', destination: '" + destinationClassName + "').");
                    ^

Error: Mapping 'CreateDepositTranQrRequest=>DepositTranQr' is invalid: Destination member 'currency' is configured, but does not exist on destination type (source: 'CreateDepositTranQrRequest', destination: 'DepositTranQr').
```

My map is a very simple createMap for testing, I have removed all others to ensure I get a good test result. Here it is

```
automapper.createMap(CreateDepositTranQrRequest, DepositTranQr)
    .forMember('currency', (opts: AutoMapperJs.IMemberConfigurationOptions) => opts.mapFrom('currency'));


automapper.assertConfigurationIsValid();
```

It states that the currency isn't available. Although I know it is. Here is the source and destination where you can see the currency exists and is public.

```
export class CreateDepositTranQrRequest {
    public currency: string;
```

and

```
export class DepositTranQr {
    public currency: string;
```

I must be using it incorrectly, but there are no concrete examples using the source and destination keys as physical classes rather than strings.

If I continue to pass in strings to the createMap rather than classes then the assertConfigurationIsValid throws a different error stating

```
throw new Error("Mapping '" + mappingKey + "' cannot be validated, since mapping.sourceType or mapping.destinationType are unspecified.");
                ^

Error: Mapping 'CreateDepositTranQrRequest=>DepositTranQr' cannot be validated, since mapping.sourceType or mapping.destinationType are unspecified.
```

Can anyone help ? Or tell me what I maybe doing wrong ?

Thanks in advance

**Comment by loedeman** [comment]
Hi @appsolutegeek, thanks for creating an issue. 

Before I try answering your question, please note validation is only a very early version of validation. I have been asked to implement validation a long while ago, but using validation in JavaScript has its (serious) limitations.

The sample that fails on you clearly shows one of those limitations. Only defining a TypeScript property does not result in the property actually being created in JavaScript. If you like to use validation, you must also initialize all properties. In the 'automapper-assertconfig-specs.ts' test file, you can see this in action:

````
class AssertConfigPropertiesProp {
    prop: string = undefined; // TODO Wiki: properties are only available when initialized: http://stackoverflow.com/a/20534039/702357
}
````

I hope this helps a bit. Should you love validation and be willing to give me a hand, feel free to create cool stuff and file a PR ;) .

Cheers, Bert
