### ISSUE TITLE
npm + typescript - import issue (example would be exellent)

### ISSUE THREAD

**Issue by dbones** [loedeman/AutoMapper#36]
Hi can you provide a Typescript + npm example using either a web project (Angular 2+ or Aurelia) or Node.JS, does not really matter which one as the code to "import" it would be similar. 

#25 <- this is very close to the issue i'm actually having, i'm currently developing a Aurelia web app.

if it helps im using VS Code as the Editor.

(ps thanks for doing this project, it should save me a ton of time)

**Comment by loedeman** [comment]
Hi @dbones , 

Thanks for your interest in the AutoMapperTS library. The library has been created quite a long while back (at least, speaking web ;)). When I created the library, the file import syntax was not that common. 

I answered a question similar to yours at StackOverflow a while ago, I hope it helps you as well: https://stackoverflow.com/questions/40138293/importing-automapper-into-a-angular2-webpack-project/44692661#44692661.

Cheers, Bert
