### ISSUE TITLE
Map (src, des)

### ISSUE THREAD

**Issue by dbones** [loedeman/AutoMapper#37]
possible enhancement

Map(srcType: string, destType: string, src: any, dest: any)

where it will override any differences from the src to the existing dest.

mainly to keep the same instance of the dest object (want 2 way binding to automatically update, as it will be observing the dest obj instance)

**Comment by loedeman** [comment]
Hi @dbones , thanks for your suggestion. Currently, I do not have enough spare time to create this functionality. Feel free though to implement this functionality yourself and file a PR ;) ... Regards, Bert
