### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by lucaritossa** [loedeman/AutoMapper#38]
I'm facing with a problem about the "ConvertToType" method and I'd like to try your unit tests with some little bit change.

Please consider I'm a newbie... so sorry for my stupid question:
I cloned your project, run "npm install" and now?

I've tried to run "karma start" but it doesn't find any test.

Could you help me?

Thx in advance!!!

**Comment by lucaritossa** [comment]
Ok, solved... **gulp** is the answer.
You defined your build/test script into GulpFile.js

**Comment by loedeman** [comment]
Hi @lucaritossa, thanks for giving the library a chance. Glad to see you already solved your own challenge ;). Happy coding!
