### ISSUE TITLE
node.js Profile usage? 

### ISSUE THREAD

**Issue by themauveavenger** [loedeman/AutoMapper#41]
Hello! I'm having trouble figuring out how to get Profiles working when using node.js. Given this example: 

```javascript
const automapper = require('automapper-ts');
const Person = require('./Person');
const OtherPerson = require('./OtherPerson');

class PeopleProfile extends automapper.Profile {
    constructor() {
        super();
        this.profileName = 'PeopleProfile';
    }

    configure() {
        this.createMap('Person', 'OtherPerson')
            .forMember('otherName', opts => opts.mapFrom('name'))
            .forMember('otherAge', opts => opts.mapFrom('age'));
    }
}
```
I am getting the following error: ```TypeError: Class extends value undefined is not a constructor or null```. Which sounds like ```Profile``` is not being exported? Can anyone point out what I'm doing wrong?

**Comment by cdunford** [comment]
We are seeing the same thing when trying to use this in a front-end angular app.

**Comment by afontaine** [comment]
It seems this is also the case in the browser as well.

![image](https://user-images.githubusercontent.com/3373136/33187513-2d4cbdcc-d060-11e7-95cf-ccb2640df020.png)
