### ISSUE TITLE
npm install automapper-ts downloads an extremely bloated __node_modules of size ~78MB

### ISSUE THREAD

**Issue by abhishekbiyala** [loedeman/AutoMapper#46]
`npm install automapper-ts` downloads an extremely bloated nested __node_modules of size ~78MB. Is this normal? I am using npm version 3.10.10.

**Comment by loedeman** [comment]
Thanks @abhishekbiyala for noticing this issue. I removed the __node_modules folder locally and published a new version to NPM which should be a lot smaller ;).
