### ISSUE TITLE
About using convertToType

### ISSUE THREAD

**Issue by alonstar** [loedeman/AutoMapper#48]
I want to use convertToType and copy all properties, how should I do ??
The code below will return an object DemoToBusinessType but no property.

	class DemoToBusinessType {

	}

	//arrange
	var objA = { ApiProperty: 'From A' };

	var fromKey = '{7AC4134B-ECC1-464B-B144-5C9D8F5B5A7E}';
	var toKey = '{2BDE907C-1CE6-4CC5-A601-9A94CA6C4737}';

	automapper
		.createMap(fromKey, toKey)
		.convertToType(DemoToBusinessType);

	// act
	var objB = automapper.map(fromKey, toKey, objA);

**Comment by lucaritossa** [comment]
Your **DemoToBusinessType** does not have any properties defined.
Automapper does not have nothing to map using the "property-name-convention".

You should try something like this: 

```typescript
class DemoToBusinessType {
   ApiProperty: string = null;
}
```

**Comment by alonstar** [comment]
I got it, thanks.
