### ISSUE TITLE
Problem with Angular CLI 6

### ISSUE THREAD

**Issue by mikelweb** [loedeman/AutoMapper#55]
Hi,
I'm using Angular CLI 6, and I don't get automapper to work.
Could you please provide a step by step integration guide for Angular CLI?? or help me to get it working.
the browser's console tells me  "ReferenceError: automapper is not defined"

I don't know how and where to place the import statement, since 
`import {} from 'automapper-ts';
`
gives an error saying that is not a module.

Thanks a lot for such an awesome library ;)

**Comment by loedeman** [comment]
Hi @mikelweb,

I assume the workaround provided in a previous issue still applies: https://github.com/loedeman/AutoMapper/issues/17. Could you please try that one? As I already mention over there, AutoMapperJS is not built with module support in mind (which were not available when starting AutoMapperJS). Using the global automapper variable should still work, though.

Cheers!

**Comment by mikelweb** [comment]
Thx a lot @loedeman
