### ISSUE TITLE
Is this project Dead?

### ISSUE THREAD

**Issue by lixaotec** [loedeman/AutoMapper#67]
Hey folks,

Its seem a long time since updates on this project.. is this a dead project?

Thanks

**Comment by patrykdawid** [comment]
I don't know if this project is dead (though it looks to be). However, I know another one that is actively developed: https://github.com/nartc/mapper

**Comment by loedeman** [comment]
Hi, I still love the project. However, I think it is technically dead indeed 😀. The alternative mentioned above is a good suggestion. Originally, this repo also was based on a port, although it has been completely rewritten since.

**Comment by lixaotec** [comment]
Thanks @patrykdawid and @loedeman !
As the owner confirms it, Ill close this comment.

Keep on rocking!
