### ISSUE TITLE
node.js support

### ISSUE THREAD

**Issue by zivni** [loedeman/AutoMapper#7]
Hi

I downloaded AutoMapper via npm to include it in my TypeScript node.js application. 
but couldn't. 
How can I import/require it?

Thanks
Ziv

**Comment by loedeman** [comment]
Hi Ziv,

Could you please tell me exactly what you are trying to do (e.g. how you install, try to reference and use the library)?

Cheers, Bert


_____________________________

**Comment by MatthewLymer** [comment]
It doesn't look like the package meets NPM specifications for use in Node.JS, specifically, it's missing the 'index.js'

Typically, you should be able to do:

    > npm install automapper-ts --save

And then use it in your project via:

    var mapper = require('automapper-ts'); // or var mapper = require("arcady-automapper");

but `mapper` is not an automapper instance.

It looks like a cool project, I am a big fan of the C# AutoMapper functionality, but this doesn't look like I can get this to work for Node.JS without doing a lot of messing around.

**Comment by loedeman** [comment]
Hi Matthew,

Thanks for the clarification!

I did not specifically build AutoMapper for use in Node.js, hence the missing index.js file. However, it does not seem a big deal for me to make that happen. If you have little time to wait, I will give it a try this week ;) ...

It would be great if you would give it a try afterwards ;) ...

Cheers! Bert





On Sat, Jan 16, 2016 at 4:48 PM -0800, "Matthew Lymer" <notifications@github.com<mailto:notifications@github.com>> wrote:


It doesn't look like the package meets NPM specifications for use in Node.JS, specifically, it's missing the 'index.js'

Typically, you should be able to do:

> npm install automapper-ts --save


And then use it in your project via:

var mapper = require('automapper-ts'); // or var mapper = require("arcady-automapper");


but mapper is not an automapper instance.

It looks like a cool project, I am a big fan of the C# AutoMapper functionality, but this doesn't look like I can get this to work for Node.JS without doing a lot of messing around.

-

**Comment by MatthewLymer** [comment]
Yes definitely, I would like to give it a try!

**Comment by loedeman** [comment]
Hi @MatthewLymer ,

I just checked in a small fix which does seem to function on my machine. Since I have limited experience in Node.js, I would be more than happy if you could give it a try!

Cheers, Bert

**Comment by loedeman** [comment]
Hi @zivni and @MatthewLymer ,

I am closing this issue, sinces there has been no communication about the fix since 14 days. Should there still be any problem using AutoMapper with Node.js, I would be more than happy to reopen this issue...

Cheers, Bert

**Comment by MatthewLymer** [comment]
Hey sorry about that, I haven't had a chance to try it out, I am planning on looking at it on the weekend, I'll let you know if it doesn't work.

**Comment by loedeman** [comment]
No problem at all @MatthewLymer ;) ... Thanks for your support, I look forward to hearing from you soon ;) ... Cheers, Bert

**Comment by MatthewLymer** [comment]
Hello Bert,
I was playing around with it in node today, and so far everything looks good, behaves as expected.

Thanks for making the change!

Cheers,
Matthew

**Comment by loedeman** [comment]
Thanks for testing Matthew! Glad it does work now ;) ! Cheers!
