### ISSUE TITLE
Ignoring not working?

### ISSUE THREAD

**Issue by dgroh** [loedeman/AutoMapper#8]
I just used the sample from the repository, but the ignore is not working. The proclaimedAge is being printed out.

Here is my code:

```ts
class Person {
    fullName: string;
    age: number;
}

class ValidatedAgeMappingProfile extends AutoMapperJs.Profile {
    public profileName = 'ValidatedAgeMappingProfile';

    public configure() {
        const sourceKey = 'ApiPerson';
        const destinationKey = 'Person';

        this.createMap(sourceKey, destinationKey)
            .forMember('proclaimedAge', (opts: AutoMapperJs.IMemberConfigurationOptions) => opts.ignore())
            .forMember('age', (opts: AutoMapperJs.IMemberConfigurationOptions) => opts.mapFrom('ageOnId'))
            .convertToType(Person);
    }
}

automapper.initialize((config: AutoMapperJs.IConfiguration) => {
    config.addProfile(new ValidatedAgeMappingProfile());
});

const sourceObject = { fullName: 'John Doe', proclaimedAge: 21, ageOnId: 15 };

automapper
    .createMap('ApiPerson', 'Person')
    .withProfile('ValidatedAgeMappingProfile');

var result = automapper.map('ApiPerson', 'Person', sourceObject);

 alert(JSON.stringify(result));
```

**Comment by loedeman** [comment]
Hi @dgroh, could you please paste your complete sample **and the compiled result in JavaScript**? The test covering this exact same functionality does work like expected. I think there is something not working as expected on your end... Cheers, Bert

**Comment by loedeman** [comment]
Excuse me @dgroh I have reconstructed your scenario. It appears you are right: when no options are specified but only withProfile() the functionality does not seem to work like expected. Expect a fix soon ;) . Thanks for reporting this bug! Cheers, Bert

**Comment by loedeman** [comment]
@dgroh A new release, v1.6.3, is just published to NPM. Thanks for your help! Cheers, Bert

**Comment by dgroh** [comment]
brilliant, thank you very much @loedeman
